# Favicon es para el icono del sitio web
favicon: assets/icon.ico
# Configuracion de titulo y descripcion del sitio web
title: " "
copyright: "2025"
description: Aplicación de escritorio para Windows, visualizar y modificar configuraciones de puertos de red.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# Muestra el apartado de descargas
show_downloads: true
# Muestra el logo en la pagina
logo: assets/logoNetPort.png
# parametros de configuracion basica de github pages
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
