title: NetPort - Configurator
description: Aplicación de escritorio para Windows, visualizar y modificar configuraciones de puertos de red.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: true
logo: assets/logoNetPort.png
github:
  zip: https://github.com/Masu-113/NetPort-Configurator